### PR TITLE
#3005: remove stale retry methods

### LINKED ISSUE #3005: Remove deprecated methods from ReadFactCast API
**Describe the bug**

retry methods deprecated since 0.5.6 can be removed from `ReadFactCast`.

### PR DESCRIPTION
**Pull request by uweschaefer**
closes #3005

### CODE REVIEW

File: factcast-core/src/main/java/org/factcast/core/DefaultFactCast.java [hunk 1]
```diff
@@ -78,11 +78,11 @@ public Set<String> enumerateTypes(@NonNull String ns) {
   @Override
   @NonNull
   @SuppressWarnings("deprecated")
```
Comment (otbe) [inline factcast-core/src/main/java/org/factcast/core/DefaultFactCast.java:80]: Can go away I think? Nothing deprecated is used

**Review by otbe — APPROVED** [review]
LGTM :)
