### PR TITLE
Issue3903 Solve EventExplorer going OOM

### LINKED ISSUE #3903: Server UI Report generation can run into OOM
**Describe the bug**
This needs some investigation, as the reporting feature is meant for – well reporting –  it should be able to handle big amounts of data by streaming it.

If it already does, then we should probably add some advice to the docs on how to configure it (grpc buffer size, instance mem min, etc)

### PR DESCRIPTION
**Pull request by bedaka**
Closes #3903

### CODE REVIEW

File: factcast-server-ui-s3-reportstore/src/test/java/org/factcast/server/ui/s3reportstore/S3ReportStoreTest.java [hunk 1]
```diff
@@ -72,40 +69,36 @@ class WhenSavingReports {
...
-      final var fileUpload = mock(Upload.class);
-      final var completedUpload = mock(CompletedUpload.class);
-      when(s3TransferManager.upload(any(UploadRequest.class))).thenReturn(fileUpload);
-      when(fileUpload.completionFuture())
-          .thenReturn(CompletableFuture.completedFuture(completedUpload));
       objectDoesNotExist();
+      final var completedUpload = mock(CreateMultipartUploadResponse.class);
+      when(s3Client.createMultipartUpload(any(CreateMultipartUploadRequest.class)))
+          .thenReturn(CompletableFuture.completedFuture(completedUpload));
+      // TODO: why no check?
```
Comment (leflamm) [inline factcast-server-ui-s3-reportstore/src/test/java/org/factcast/server/ui/s3reportstore/S3ReportStoreTest.java]: can go?
